version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - './volumes/mongo:/data/db'

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kdavydovskyi
      - POSTGRES_PASSWORD=1234
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'